version: '3.8'

services:
  postgres_db:
    image: "postgres:15-alpine"
    restart: "no"
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./dump_file.sql:/docker-entrypoint-initdb.d/dump_file.sql
